### ISSUE TITLE
Waterfall layout

### ISSUE THREAD

**Issue by denis-obukhov** [jVirus/compositional-layouts-kit#5]
Is it possible to create a waterfall/Pinterest layout? 

![image](https://user-images.githubusercontent.com/63708833/92459001-55abf800-f1f0-11ea-824d-fb4995b53b51.png)

**Comment by eleev** [comment]
Yes, it's possible. The approach I would recommend is based on fractional computation for each layout cell, based on the data source items. The repo contains hints on how to do that. 

Feel free to share your solution or make a pull request
