### ISSUE TITLE
Is It Possible to estimated Height in waterfallayout?

### ISSUE THREAD

**Issue by maulikshah09** [jVirus/compositional-layouts-kit#6]

**Comment by maulikshah09** [comment]
I tried using composite layout it is look like below image.. Please help me to solve this issue.

**Campsite layout code.**

```
  let itemSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1.0), heightDimension: .estimated(50))
        let item = NSCollectionLayoutItem(layoutSize: itemSize)
                
        let groupSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1.0), heightDimension: .estimated(50))
        let group = NSCollectionLayoutGroup.horizontal(layoutSize: groupSize, subitem: item, count: 2)

        let section = NSCollectionLayoutSection(group: group)
                
        let layout = UICollectionViewCompositionalLayout(section: section)
        return layout
```

![Simulator Screen Shot - iPhone 11 Pro Max - 2021-12-07 at 19 02 25](https://user-images.githubusercontent.com/11289579/145038341-3fe4abdb-fe4d-4acb-bccd-58bd59da54d7.png)

**Comment by eeshishko** [comment]
Hey @maulikshah09 !
To make waterfall-like compositional layout, you should use custom `NSCollectionLayoutGroup.custom` API. You can try this SPM package with my adjustments in [this PR](https://github.com/lucamegh/Niagara/pull/1) - it allows to archive exactly what you want. If you have any questions, feel free to reach me through github or email.

**Comment by eleev** [comment]
Thanks @eeshishko a lot!
